### ISSUE TITLE
Weather Update Interval 

### ISSUE THREAD

**Issue by jakegarris5** [ItsRiprod/DeskThing#13] opened 2024-07-17 03:27 UTC
During normal use, the weather seems to "forget" to update, even with the update interval set to 0.15 (15 minutes). To get updated weather, I have to exit out of the weather applet on the CarThing and re-enter it.

**Comment by ItsRiprod** [comment] 2024-07-17 03:34
"It's not a feature, it's a bug" *not really-*

Same goes for both the spotify app and mediawin apps actually. And no, it's not a bug. But no, it won't stay around. The "refresh interval" is how often it pulls from local storage vs from the API - not an automatic refresh (yet) but I have the functionality there so when I add it down the road, it's a lot easier to add.

Spotify and mediamin both don't pull again several seconds into a song, as the setting may suggest, as well simply because I haven't implemented it yet- 

This is also something else I plan on adding here soon (maybe v0.5.6?) 

But thanks for pointing this out!

**Comment by ItsRiprod** [comment] 2024-09-11 20:30
Fixed in the latest weather app! Updates every 15 minutes (how often the weather API updates) and there is no longer a limit on requests per day

**Closed by ItsRiprod** 2024-09-11 20:30 UTC
